# Generated by Django 5.0.6 on 2024-06-17 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(blank=True, max_length=100, null=True)),
                ("prenom", models.CharField(blank=True, max_length=100, null=True)),
                ("email", models.CharField(blank=True, max_length=100, null=True)),
                ("adresse", models.CharField(blank=True, max_length=255, null=True)),
                ("telephone", models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Livreur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(blank=True, max_length=100, null=True)),
                ("statut", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "position_geo",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Produit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom_produit",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "prix",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "type_produit",
                    models.CharField(
                        blank=True,
                        choices=[("plat", "Plat"), ("dessert", "Dessert")],
                        max_length=7,
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Commande",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_commande", models.DateTimeField(blank=True, null=True)),
                (
                    "montant_total",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("statut", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "frais_livraison",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                (
                    "temps_estime_livraison",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="backoffice.client",
                    ),
                ),
                (
                    "livreur",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="backoffice.livreur",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Paiement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "montant",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "methode_paiement",
                    models.CharField(
                        blank=True,
                        choices=[("stripe", "Stripe"), ("especes", "Espèces")],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "statut_paiement",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("en_attente", "En attente"),
                            ("paye", "Payé"),
                            ("annule", "Annulé"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("date_paiement", models.DateTimeField(blank=True, null=True)),
                (
                    "commande",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="backoffice.commande",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CommandeProduit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantite", models.IntegerField(blank=True, null=True)),
                (
                    "commande",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="backoffice.commande",
                    ),
                ),
                (
                    "produit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="backoffice.produit",
                    ),
                ),
            ],
        ),
    ]
