# Generated by Django 5.0.6 on 2024-06-18 12:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backoffice", "0012_remove_livreur_nom_livreur_user_alter_client_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produit",
            name="type_produit",
            field=models.CharField(
                blank=True,
                choices=[
                    ("plat", "Plat"),
                    ("dessert", "Dessert"),
                    ("boissons", "Boissons"),
                    ("pizza", "Pizza"),
                ],
                max_length=255,
                null=True,
            ),
        ),
    ]
