# Generated by Django 5.0.6 on 2024-06-19 09:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backoffice", "0013_alter_produit_type_produit"),
    ]

    operations = [
        migrations.AddField(
            model_name="produit",
            name="statut",
            field=models.CharField(
                choices=[
                    ("disponible", "Disponible"),
                    ("indisponible", "Indisponible"),
                ],
                default="disponible",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="livreur",
            name="statut",
            field=models.CharField(
                blank=True,
                choices=[
                    ("disponible", "disponible"),
                    ("en_cours_de_livraison", "En cours de livraison"),
                    ("indisponible", "indisponible"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
