# Generated by Django 5.0.6 on 2024-06-20 10:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backoffice", "0018_produit_date_creation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produit",
            name="date_creation",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Date de Création"
            ),
        ),
    ]
