# Generated by Django 5.0.6 on 2024-06-17 12:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backoffice", "0002_alter_commande_statut_alter_livreur_statut"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commande",
            name="temps_estime_livraison",
            field=models.DurationField(blank=True, null=True),
        ),
    ]
