# Generated by Django 5.0.6 on 2024-06-17 15:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backoffice", "0004_alter_commande_temps_estime_livraison"),
    ]

    operations = [
        migrations.AddField(
            model_name="produit",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="produits/"),
        ),
    ]
