# Generated by Django 5.0.6 on 2024-06-17 20:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backoffice", "0009_remove_client_email_remove_client_nom_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="nom",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="client",
            name="prenom",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
