# Generated by Django 5.0.6 on 2024-06-19 17:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backoffice", "0015_alter_client_user_alter_livreur_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="paiement",
            name="payment_token",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Token de Paiement"
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="telephone",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Le numéro de téléphone doit être entré au format '+999999999'. Jusqu'à 15 chiffres autorisés.",
                        regex="^\\+?1?\\d{9,15}$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="commande",
            name="montant_total",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="commande",
            name="statut",
            field=models.CharField(
                blank=True,
                choices=[
                    ("en_cours", "En cours"),
                    ("prise_en_charge", "Prise en charge"),
                    ("en_cours_de_livraison", "En cours de livraison"),
                    ("livree", "livrée"),
                ],
                default="en_cours",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="paiement",
            name="statut_paiement",
            field=models.CharField(
                blank=True,
                choices=[
                    ("en_attente", "En attente"),
                    ("paye", "Payé"),
                    ("annule", "Annulé"),
                ],
                default="en_attente",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="produit",
            name="type_produit",
            field=models.CharField(
                blank=True,
                choices=[
                    ("plat", "Plat"),
                    ("dessert", "Dessert"),
                    ("boissons", "Boissons"),
                    ("pizza", "Pizza"),
                ],
                default="plat",
                max_length=255,
                null=True,
            ),
        ),
    ]
