# Generated by Django 5.0.6 on 2024-06-19 22:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backoffice", "0016_paiement_payment_token_alter_client_telephone_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paiement",
            name="methode_paiement",
            field=models.CharField(
                blank=True,
                choices=[("", ""), ("stripe", "Stripe"), ("especes", "Espèces")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="produit",
            name="prix",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=5, null=True
            ),
        ),
    ]
